version: '3.7'

services:
  node:
    image: config-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - default

networks:
  default:
    driver: bridge