version: '3.7'

services:
  node:
    image: discovery-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - default

networks:
  default:
    driver: bridge