version: '3.7'

services:
  config-server:
    image: config-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        discoveryhost: discovery-server
        discoveryport: 8761      
    ports:
      - "8888:8888"
    networks:
      - default
    environment:
      - discoveryhost=discovery-server
      - discoveryport=8761

networks:
  default:
    driver: bridge